# Generated by Django 3.1.2 on 2021-07-11 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 11, 14, 37, 11, 749536, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
